services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sarvar55/karar-app:v1.0.0
    container_name: karar-app
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    container_name: karar-db
    restart: always
    env_file:
      - .env.db.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
