spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/karadb}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  config:
    activate:
      on-profile: prod

server:
  port: 8080

logging:
  level:
    root: WARN
    org.karar.dev: INFO
    org.springframework: WARN
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
  file:
      name: logs/karar-prod.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 50
      total-size-cap: 1GB