spring:
  application:
    name: karar.dev
  profiles:
    active: ${PROFILE:dev}

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %red([%thread]) %highlight(%-5level) %yellow(%-40.40logger{39}:%L) - %msg%n}

server:
  port: ${PORT:8080}